import { useRouter } from "next/router";
import { collection, doc, getDoc, getDocs, onSnapshot } from "firebase/firestore";
import { useEffect, useState } from "react";
import { db } from "../../../firebase/firebase";
import Head from "next/head";
import Image from "next/image";
import ConcertInfo from "@/components/ConcertInfo";

export async function getServerSideProps(router) {
    const idObj = router.query;
    const { id } = idObj;

    return {
        props: {
            id,
        },
    };
}

function SpecificConcert({ id }) {
    const [screenWidth, setScreenWidth] = useState(0);
    const [concertData, setConcertData] = useState([]);
    const router = useRouter();

    useEffect(() => {
        // GET concert info by ID from firebase
        onSnapshot(doc(db, "concerts", id), (doc) => {
            setConcertData(doc.data());
        });
        function handleResize() {
            setScreenWidth(window.innerWidth);
        }
        window.addEventListener("resize", handleResize);
        handleResize();
        return () => {
            window.removeEventListener("resize", handleResize);
        };
    }, []);
    console.log(concertData.concertImage);
    return (
        <>
            <Head>
                <title>Movcert - {concertData.title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-cover bg-center h-[700px]" style={{ backgroundImage: `url(${concertData.concertImage})`}} data-aos="fade">
                <div className="absolute top-0 bottom-0 right-0 left-0 bg-gradient-to-b from-black h-[140px]" />
                <div className="absolute h-[700px] top-0 bottom-0 right-0 left-0 w-screen bg-black/40 z-0 " />
                <div className="flex justify-center items-center text-black">
                    <div className="z-10 mt-[320px]">
                        <div className=" block w-screen p-8 mt-[270px] border rounded-lg shadow-md bg-white z-10 abovesm:w-[550px] md:w-[800px]" data-aos="fade-up">
                            <h1 className="text-center text-2xl">{concertData.title}</h1>
                        </div>
                    </div>
                </div>
                <div className="mt-8 p-4">
                    <ConcertInfo concertData={concertData}/>
                </div>
            </div>
        </>
    );
}

export default SpecificConcert;
