import Head from "next/head";
import Link from "next/link";
import { UserAuth } from "@/context/AuthContext";
import { useState } from "react";
import { useRouter } from "next/router";

function Register() {
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const { user, signUp } = UserAuth();
    let router = useRouter();

    async function handleSubmit(e) {
        e.preventDefault();
        try {
            await signUp(email, password);
            router.back();
        } catch (error) {
            console.log(error);
        }
    }

    return (
        <>
            <Head>
                <title>Movcert - Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="h-screen bg-cover custom-img" data-aos="fade">
                <div className="flex items-center justify-center">
                    <div className="absolute top-0 bottom-0 right-0 left-0 bg-gradient-to-b from-black h-[140px]" />
                    <div className="absolute top-0 bottom-0 right-0 left-0 bg-black/40 h-screen" />
                    <div
                        className="block w-[500px] p-8 mt-[150px] border rounded-lg shadow-md bg-white z-10 abovesm:w-[550px]"
                        data-aos="fade-up"
                    >
                        <h1 className="text-3xl text-black">Register</h1>
                        <form onSubmit={handleSubmit}>
                            <input
                                onChange={(e) => setEmail(e.target.value)}
                                type="email"
                                placeholder="Email"
                                className=" my-4 border-2 border-[##ced4da] h-[50px] p-2 w-full outline-none rounded shadow-sm focus:border-[#f3c07a] "
                                autoComplete="email"
                            />
                            <input
                                onChange={(e) => setPassword(e.target.value)}
                                type="password"
                                placeholder="Password"
                                className="my-2 border-2 border-[##ced4da] h-[50px] p-2 w-full outline-none rounded shadow-sm focus:border-[#f3c07a] "
                                autoComplete="current-password"
                            />
                            <div className="flex justify-center items-center">
                                <button className=" bg-[#ffba5a] text-white w-[120px] h-[50px] mt-6 rounded-full shadow-md ">
                                    Register
                                </button>
                            </div>
                            <div>
                                <p className="mt-6 text-sm text-right text-gray-600">
                                    Already have an account?{" "}
                                    <span className="text-[#ffba5a] font-bold">
                                        <Link href="login">Login</Link>
                                    </span>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </>
    );
}

export default Register;
